// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SNDI.Data;

#nullable disable

namespace SNDI.Migrations
{
    [DbContext(typeof(SNDIContext))]
    [Migration("20230815103659_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SNDI.Models.Document", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Circonscription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommuneDeNaissance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDenaissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domicile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuxEtablissement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuxNaissance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationnalite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDeFamille")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDeJeuneFille")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NombreEnfant")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDePiece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDeTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaysNaissance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationMatrimoniale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDepiece")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("SNDI.Models.Filiation", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateDenaissanceMere")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDenaissancePere")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LieuxNaissanceMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuxNaissancePere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenomMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenomPere")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Filiation");
                });

            modelBuilder.Entity("SNDI.Models.Filiation", b =>
                {
                    b.HasOne("SNDI.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.Navigation("Document");
                });
#pragma warning restore 612, 618
        }
    }
}
